#!/bin/sh

EXPECTED_HOOKS_PATH=".githooks"
CURRENT_HOOKS_PATH=$(git config --get core.hooksPath)

if [ "$CURRENT_HOOKS_PATH" != "$EXPECTED_HOOKS_PATH" ]; then
  echo "❌ Hooks Git non installés."
  echo "👉 Exécute : scripts/setup.ps1"
  exit 1
fi

echo "Bump automatique de version..."

powershell -ExecutionPolicy Bypass -File ./bump-version.ps1

if [ $? -ne 0 ]; then
  echo "❌ Échec du bump de version. Commit annulé."
  exit 1
fi

echo "✅ Version bumpée et synchronisée."
